### ISSUE TITLE
Software Quality factors, metrics, testing coverage

### ISSUE THREAD

**Issue by aymansalama** [aymansalama/WikiDownloaderWeb#10]
Please make sure to cover the below points: Test cases/Paths/Scenarios & Coverage: Design the test cases and scenarios based on the quality standards below, and explain and justify accordingly (in your report): § Software quality factors
§ Testing Coverage
§ Line coverage
§ Function coverage § Black/white box testing
§ Equivalence class (EC)
§ Boundary Value Analysis § Cyclomatic Complexity
§ SW Testing Strategies
§ Unit Testing.
§ Integration Testing. § System Testing.

**Comment by yewjun** [comment]
All the testing have covered in the report except Cyclomatic Complexity, Line Coverage and Equivalence Class (EC)
